auto:	          true

markdown:         rdiscount
pygments:         true
paginate:         6
permalink:        /:title

title:            Viney
url:              http://viney.github.com
feed:             /atom.xml
author:
    name:         Viney
    twitter:      twitter.com/vineychow
description:      "Viney的博客"
author_info:      <a href="http://viney.github.com/about">Viney</a>

copyright:
    - &copy; Copyright 2012-13 <a href="http://viney.github.com" title="Viney" target="_blank">Viney</a>
